### ISSUE TITLE
u ratted android for this src which he bought from me pasta

### ISSUE THREAD

**Issue by homeless1337** [paster0001/fortnite-internal-season-7#1]

**Comment by array1338** [comment]
False information, someone sent me it today.

**Comment by android1337** [comment]
Who?

**Comment by AgentFN** [comment]
My discord alex fr#4461 helppppp

**Comment by AgentFN** [comment]
plsssssss

**Comment by AgentFN** [comment]
> False information, someone sent me it today.

I can get help pls

**Comment by android1337** [comment]
@AgentFN  you are retarded, oh wait I still have your message https://i.imgur.com/YElm4Md.jpg

**Comment by PastoThePaster** [comment]
> @AgentFN you are retarded, oh wait I still have your message https://i.imgur.com/YElm4Md.jpg

Ida is obfuscator!!!!
